# Generic bootstrapping .bashrc
source_all() {
  if [[ -d "$1" ]]; then
    for script in "$1"/*; do
      [ -x "$script" ] && source "$script"
    done
  else
    echo "$1 is not a directory!" >&2
    return 1
  fi
}

source_all ~/.bashrc.d

# Put stuff in here if you don't want it checked in
[ -e ~/.bash-secure ] && source ~/.bash-secure
