# Generic bootstrapping .bashrc
source_all() {
  if [[ -d "$1" ]]; then
    for script in "$1"/*; do
      source "$script"
    done
  else
    echo "$1 is not a directory!" >&2
  fi
}

source_all ~/.bashrc.d