#!/usr/bin/env bash

# Pre-push hook
#
# Install:
#   If you're using my gitconfig, copy to wherever core.hooksPath points
#   (~/repos/.git-hooks by default). If you're not, copy to .git/hooks/ in the
#   repo where you want to use the hook (or merge this content with an
#   existing pre-push file there).
#          
#   Make sure it's executable!
#
# Warns about pushing to master, prompts user to switch to another branch
# Dependencies: pushb, pr, and switch aliases (see ~/.gitconfig)

if [ "$(git symbolic-ref --short HEAD)" == 'master' ]; then
  #wc reads from stdin by default
  [ "$(wc -l)" -le 0 ] && exit  #no refs pushed, nothing to do

  echo "You are pushing to MASTER! Are you sure you want to continue?"
  echo "Enter the name of a new branch to switch all of your commits to, or if you're sure,"
  echo "enter "'"'"I'm sure I want to push to master"'"'" (or CTRL+C to exit)"
  exec < /dev/tty   #see http://stackoverflow.com/questions/3417896/how-do-i-prompt-the-user-from-within-a-commit-msg-hook
  read -p '> ' input
  [ "$input" = "I'm sure I want to push to master" ] && exit 0
  
  git switch $input
  git pushb
  
  sleep .1  #github takes a sec to register the branch
  git pr
  
  exit 1  #blocks original push
fi